### ISSUE TITLE
"is_local" Not Disabling HTTPS (Local)

### ISSUE THREAD

**Issue by lKinx** [coroniumcloud/Coronium-LS#1]
The following code does not disable HTTPS. As far as I understand in the docs, **is_local should disable HTTPS when set to true.** I found no evidence of it doing so in the cloud.lua file.
```
    local coronium = require('coronium.cloud')
    local cloud = coronium:new({
        host = "192.168.71.73",
        app_key = "756429bc-52c9-11e6-b0ec-080027665987",
        is_local = true
}
```

To disable HTTPS, I had to set "https = false" in the table.

**Comment by coroniumcloud** [comment]
Sorry, you also need to add `https = false`

**Comment by coroniumcloud** [comment]
I'll update the docs. Thanks!

**Comment by coroniumcloud** [comment]
Fixed.

**Comment by coroniumcloud** [comment]
Thanks for pointing out the `is_local`, was some leftover. All fixed up.

Cheers.
