### ISSUE TITLE
Template Issue

### ISSUE THREAD

**Issue by lKinx** [coroniumcloud/Coronium-LS#10]
All of your instances of ".tpl" files have "page.title" or something of the sort in the file. The  Lua-Resty Template module does not recognize "page" as a variable. Rather, all instances of "page." should be removed.

I found instances of this occurring in your "index.tpl" files, as well as the Template and Generating Pages docs.

For example,
```
<!-- tpl/index.tpl -->
<html>
<head>
  <title>{{ page.title }}</title>
  ...
</head>
<body>
  <div>{{ page.content }}</div>
</body>
</html>
```

Should be
```
<!-- tpl/index.tpl -->
<html>
<head>
  <title>{{ title }}</title>
  ...
</head>
<body>
  <div>{{ content }}</div>
</body>
</html>
```

**Comment by coroniumcloud** [comment]
Could be a doc issue, the code that would go along with that .tpl would look like this:

```
local tpl = {
  page = {
    title = "My Page",
    content = "My Content"
  }
}

cloud.template.render('index.tpl', tpl)
```

The page data should be wrapped in a "content" table to you can pass different data and structures.

It's meant to demonstrate pushing complex tables at the template. There still needs to be an example set up though.

**Comment by develephant** [comment]
Documentation issue. This is the proper usage.

Thanks for reporting.
