### ISSUE TITLE
MySQL orderby and limit Don't Work

### ISSUE THREAD

**Issue by lKinx** [coroniumcloud/Coronium-LS#12]
Currently, line 200-202 in mysql.lua reads:
```
    self.orderby = select_tbl.orderby or nil
    ...
    if order then
      table.insert(qt, cloud.sf("ORDER BY %s", self.order))
    end
```
However, both "order" and "self.order" are always nil. To fix it, I tried to follow your doc syntax, saying that the "orderby" table takes a "colName" and "direction" value.

I believe that it should read:
```
    if self.orderby then
      table.insert(qt, cloud.sf("ORDER BY %s %s", self.orderby.colName, self.orderby.direction))
    end
```

This may not be the best implementation, as it only allows one column sort direction, whereas I know that MySQL can allow multiple (see http://dev.mysql.com/doc/refman/5.7/en/sorting-rows.html). The MySQL docs page example would need to be updated as well.

Additionally, I believe that the limit property will also have an error, as "limit" too appears to always be nil:
```
    if limit then
      table.insert(qt, cloud.sf("LIMIT %d", self.limit))
    end
```

**Comment by coroniumcloud** [comment]
Thanks for catching this, will take a look.

**Comment by txzeenath** [comment]
Oopse. Playing with git lol

**Comment by develephant** [comment]
I believe this has been added to dev. Thanks!
