### ISSUE TITLE
Public App Module Sharing System

### ISSUE THREAD

**Issue by coroniumcloud** [coroniumcloud/Coronium-LS#5]
Create a system to share __App Modules__ via Coronium `cloud-tools`, similar to npm.

 - Developer posts App Module to a GitHub repo with meta.lua.
 - Using the cloud-tools, add to central LS modules database.

## Additions needed for cloud-tools:

```
cloud register <email>
cloud deregister <email>

cloud share <mod_name>
cloud install <mod_name>

cloud search <mod_query>
```

## Meta file schema? (meta.lua)

```
return
{
  name    = 'MailGun',
  version = '1.0.0',
  author  = 'Coronium Developer',
  hash    = <generated>,
  repo    = 'https://github.com/author/repo_name.git',
  docs    = 'http://readthedocs.org/mailgun-ls/',
  site    = 'https://www.mydevelopersite/mymodule_info'
}
```

**Comment by StevenWarren** [comment]
Chris, 

I like this idea of having a module system. It might be a nice idea to have a repo dedicated to contributions. Take a look at the Spree Commerce project to see an example of how they are doing it.

Spree: https://github.com/spree/spree
Contributions: https://github.com/spree-contrib

**Comment by StevenWarren** [comment]
Just thought about it. There is an older project written for Corona, CIPR. This might have some ideas on how to implement something of this nature. Not sure if the author is still active in the Corona community.

CIPR: https://github.com/six8/corona-cipr

**Comment by coroniumcloud** [comment]
Thanks for tips Steve, will check them out.

**Comment by develephant** [comment]
Converting to plugin system.
