### ISSUE TITLE
cloud.sqlstr should be cloud.mysql.string

### ISSUE THREAD

**Issue by lKinx** [coroniumcloud/Coronium-LS#7]
In the file "mysql.lua" in the "lualib/cloud" folder, all instances of "cloud.sqlstr" should be replaced with "cloud.mysql.string". I have a feeling this was caused by your recent refactoring of the source. Should be a quick fix. :)

I also found one instance of "cloud.sqlstr" in the "databag:update" example in the docs.

Keep up the great work!

**Comment by coroniumcloud** [comment]
Thanks, I knew there was probably some hanging around still. Really appreciate it.

**Comment by coroniumcloud** [comment]
Should be fixed in 1.2.1

Thanks!
